### ISSUE TITLE
Incorrect code generation [Cannot read property get of undefined]

### ISSUE THREAD

**Issue by a76** [thewalkingtoast/broccoli-ember-script#1]
I use ember-script with ember-cli. The following ember script:

`import Ember from "ember"`

class LoginController extends Ember.ObjectController
  login: "Test"

`export default LoginController`
Is incorrectly compiled to the javascript below:

define("cca/controllers/login", 
  ["ember","exports"],
  function(__dependency1__, __exports__) {
    "use strict";
    // Generated by EmberScript 0.0.14
    var LoginController;
    var get$ = Ember.get;
    var Ember = __dependency1__["default"];
    LoginController = Ember.ObjectController.extend({ login: 'Test' });
    __exports__["default"] = LoginController;
  });//# sourceURL=cca/controllers/login.js
The problem is that the get$ variable is resolved [assigned] before the Ember variable. As a result the 'Cannot read property get of undefined' exception is raised in the run time.

I have seen discussion devoted to it here https://github.com/stefanpenner/ember-cli/issues/1368 and
here https://github.com/ghempton/ember-script/issues/44
But I don't understand who is responsible for it and when it will be resolved...

Could you please suggest any ideas or workarounds?

**Comment by coladarci** [comment]
The fact that no one has even commented on this leads me to believe that ember-script is officially dead. Sad day for large code bases.

**Comment by kristianmandrup** [comment]
I fixed this last year with my fork of emberscript:

https://github.com/kristianmandrup/ember-cli-emberscript

Try to use this as a base and see where that gets you ;) Also ask on the official github emberscript issues list.  See f.ex https://github.com/ghempton/ember-script/issues/44

**Comment by thewalkingtoast** [comment]
@coladarci This is just a thin wrapper around ember script to hook into the Broccoli process and does not have any control over the generation of code from within ember script. Follow @kristianmandrup's suggestions. :smiley:
